{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.\n",
    "\n",
    "push(x) -- Push element x onto stack.\n",
    "pop() -- Removes the element on top of the stack.\n",
    "top() -- Get the top element.\n",
    "getMin() -- Retrieve the minimum element in the stack.\n",
    " \n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "8\n",
      "7\n",
      "5\n"
     ]
    }
   ],
   "source": [
    "#1  先用list試試看\n",
    "class MinStack:\n",
    "    def __init__(self):\n",
    "        self.stack=[]\n",
    "\n",
    "    def push(self,x):\n",
    "        self.stack.append(x)  \n",
    "   \n",
    "    def pop(self):\n",
    "        self.stack.pop()\n",
    "    \n",
    "    def top(self):\n",
    "        return self.stack[-1]\n",
    "    \n",
    "    def getMin(self):\n",
    "        return min(self.stack)\n",
    "\n",
    "astack=MinStack()\n",
    "astack.push(5)\n",
    "astack.push(6)\n",
    "astack.push(7)\n",
    "astack.push(8)\n",
    "print(astack.top())\n",
    "astack.pop()\n",
    "print(astack.top())\n",
    "print(astack.getMin())\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--push--\n",
      "8\n",
      "---\n",
      "89\n",
      "---\n",
      "8910\n",
      "---\n",
      "\n",
      "--getMin--\n",
      "8\n",
      "--top--\n",
      "10\n",
      "--pop--\n",
      "89\n",
      "---\n",
      "8\n",
      "---\n"
     ]
    }
   ],
   "source": [
    "#2   用linked list 寫寫看\n",
    "\n",
    "class Node:\n",
    "    def __init__(self,val):\n",
    "        self.val=val\n",
    "        self.next=None\n",
    "    \n",
    "class MinStack:\n",
    "    def __init__(self):\n",
    "        self.head=None\n",
    "        self.size=0\n",
    "    \n",
    "    \n",
    "    def push(self, x: int) -> None:\n",
    "        \n",
    "        if self.head is None:\n",
    "            self.head=Node(x)\n",
    "        else:\n",
    "            cur=self.head\n",
    "            while cur.next is not None:\n",
    "                cur = cur.next\n",
    "            node=Node(x)\n",
    "            cur.next=node\n",
    "        self.size+=1\n",
    "                    \n",
    "    def pop(self) -> None:\n",
    "        \n",
    "        if self.head is None:\n",
    "            return\n",
    "        else:\n",
    "            index=self.size\n",
    "            cur=self.head\n",
    "            for _ in range(index-2):\n",
    "                cur = cur.next\n",
    "            cur.next=None\n",
    "        self.size-=1\n",
    "\n",
    "    \n",
    "    def top(self) -> int:\n",
    "        \n",
    "        if self.head is None:\n",
    "            return\n",
    "        else:\n",
    "            cur=self.head\n",
    "            while cur.next is not None:\n",
    "                cur=cur.next\n",
    "            return cur.val\n",
    "        \n",
    "\n",
    "    def getMin(self) -> int:   ## n個數字、比 n-1 次，每次暫存比較小的值\n",
    "        \n",
    "        if self.head is None:\n",
    "            return\n",
    "        else:\n",
    "            \n",
    "            index=self.size\n",
    "            cur=self.head\n",
    "            temp=cur.val\n",
    "            for _ in range(index-1):\n",
    "                if temp < cur.next.val:\n",
    "                    temp=temp\n",
    "                \n",
    "                else:\n",
    "                    temp=cur.next.val\n",
    "                cur=cur.next\n",
    "        print(temp)\n",
    "    \n",
    "        \n",
    "    def pprint(self):\n",
    "        \n",
    "        cur=self.head\n",
    "        \n",
    "        print(cur.val,end='')\n",
    "        while cur.next is not None:\n",
    "            cur=cur.next\n",
    "            print(cur.val,end='')\n",
    "            \n",
    "        print('')\n",
    "        print('---')\n",
    "            \n",
    "            \n",
    "        \n",
    "print('--push--')        \n",
    "stack=MinStack()\n",
    "stack.push(8)\n",
    "stack.pprint()\n",
    "stack.push(9)\n",
    "stack.pprint()\n",
    "stack.push(10)\n",
    "stack.pprint()\n",
    "\n",
    "print('')\n",
    "print('--getMin--')    \n",
    "stack.getMin()\n",
    "\n",
    "print('--top--')    \n",
    "print(stack.top())\n",
    "\n",
    "print('--pop--')    \n",
    "stack.pop()\n",
    "stack.pprint()\n",
    "stack.pop()\n",
    "stack.pprint()\n",
    "\n",
    "#在leetcode裡面答案對，但沒辦法被Accept，應該是getMin的方式有問題\n",
    "##檢討：更改getMin的方式，每當push進去時則比較"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-3\n",
      "0\n",
      "-2\n"
     ]
    }
   ],
   "source": [
    "#3 理解完老師的解答，自己練習打 \n",
    "class Node:\n",
    "    def __init__(self, val, nextNode=None):\n",
    "        self.val=val\n",
    "        self.topNode_Min=val  #每新增一個節點，存著此節點(top)以下的最小值\n",
    "        self.next=nextNode\n",
    "    \n",
    "\n",
    "\n",
    "class MinStack:\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"\n",
    "        initialize your data structure here.\n",
    "        \"\"\"\n",
    "        self.topNode=None   ### 起初格式：沒有任何節點\n",
    "\n",
    "    def push(self, x: int) -> None:\n",
    "        if self.topNode == None:\n",
    "            self.topNode=Node(x,None)\n",
    "        else:\n",
    "            temp=self.topNode.topNode_Min\n",
    "            \n",
    "            newNode=Node(x, self.topNode) #建立一個新的節點[[.next指標為self.topNode]]!!!!!!\n",
    "            self.topNode=newNode          #.topNode改為新建的節點\n",
    "            \n",
    "            if temp < self.topNode.val :\n",
    "                self.topNode.topNode_Min=temp\n",
    "        \n",
    "\n",
    "    def pop(self) -> None:\n",
    "        self.topNode=self.topNode.next\n",
    "        \n",
    "\n",
    "    def top(self) -> int:\n",
    "        return self.topNode.val\n",
    "        \n",
    "\n",
    "    def getMin(self) -> int:\n",
    "        return self.topNode.topNode_Min\n",
    "        \n",
    "\n",
    "\n",
    "# Your MinStack object will be instantiated and called as such:\n",
    "minStack = MinStack();\n",
    "minStack.push(-2);\n",
    "minStack.push(0);\n",
    "minStack.push(-3);\n",
    "print(minStack.getMin());   #--> Returns -3.\n",
    "minStack.pop();\n",
    "print(minStack.top());      #--> Returns 0.\n",
    "print(minStack.getMin());   #--> Returns -2.\n",
    "\n",
    "##發現當pop掉最後一個數字，程是會找不到topNode，可能指標上有出問題\n",
    "##發現在push建立新節點時，[[.next指標為self.topNode]]!!!!!!\n",
    "##結論：原來一開始在思考時指標就想錯方向，指標應該指向盤子下方的數字，因為只能找到盤子下方的數字，所以當拿掉最上面的時候，才能找到top！"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-3\n",
      "0\n",
      "-2\n"
     ]
    }
   ],
   "source": [
    "## 老師的參考解答\n",
    "class Node:\n",
    "    def __init__(self, val, nextNode=None):\n",
    "        self.val = val\n",
    "        self.temp_min = val\n",
    "        self.next = nextNode\n",
    "\n",
    "class MinStack:\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"\n",
    "        initialize your data structure here.\n",
    "        \"\"\"\n",
    "        self.topNode = None\n",
    "    def push(self, x: int) -> None:\n",
    "        if self.topNode is None:\n",
    "            self.topNode = Node(x, None)\n",
    "        else:\n",
    "            temp = self.topNode.temp_min\n",
    "            self.topNode = Node(x, self.topNode)\n",
    "            if temp < self.topNode.val:\n",
    "                self.topNode.temp_min = temp\n",
    "                \n",
    "    def pop(self) -> None:\n",
    "        self.topNode = self.topNode.next\n",
    "\n",
    "    def top(self) -> int:\n",
    "        return self.topNode.val\n",
    "\n",
    "    def getMin(self) -> int:\n",
    "        return self.topNode.temp_min\n",
    "\n",
    "minStack = MinStack();\n",
    "minStack.push(-2);\n",
    "minStack.push(0);\n",
    "minStack.push(-3);\n",
    "print(minStack.getMin());   #--> Returns -3.\n",
    "minStack.pop();\n",
    "print(minStack.top());      #--> Returns 0.\n",
    "print(minStack.getMin());   #--> Returns -2.\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
